name:                RelationalAlgebra
version:             0.1.0.0
github:              "hubbards/relational-algebra"
license:             MIT
author:              "Spencer Hubbard"
copyright:           "2018 Spencer Hubbard"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hubbards/relational-algebra>

dependencies:
- base >= 4.7 && < 5
- pretty
- doctest

library:
  source-dirs: src
